import { StyleSheet, Dimensions, Platform } from "react-native";
import colors from "./colors";
import typography from "./fonts";
const { width, height } = Dimensions.get('window');
export default StyleSheet.create({
  screen: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  mainContent: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  card: {
    width: "100%",
    maxWidth: 310,
    backgroundColor: "rgba(255,255,255,0.14)",
    borderRadius: 28,
    paddingVertical: 30,  
    paddingHorizontal: 15,
    alignItems: "center",
  },
  logo: {
    width: 115,
    height: 115,
    marginBottom: 18,
    resizeMode: "contain",
  },
  title: {
    fontFamily: typography.bold,
    fontSize: 26,
    color: colors.textPrimary,
    marginBottom: 12,
    textAlign: "center",
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
  },
  subtitle: {
    fontFamily: typography.regular,
    fontSize: 15,
    textAlign: "center",
    color: colors.textPrimary,
    opacity: 0.85,
    lineHeight: 22,
    marginBottom: 35,
    paddingHorizontal: 10,
  },
  inputContainer: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 14,
    height: 45,
    justifyContent: "center",
    paddingHorizontal: 18,
    marginBottom: 30,
    borderWidth: 0,
    borderColor: 'transparent',
  },
  input: {
    fontFamily: typography.regular,
    fontSize: 16,
    color: "#000",
    paddingVertical: 0,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  buttonContainer: {
    width: "100%",
    alignItems: "center",
  },
  button: {
    width: "70%",
    height: 45,
    borderRadius: 26,
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 25,
  },
  buttonText: {
    color: "#fff",
    fontFamily: typography.bold,
    fontSize: 18,
    fontWeight: Platform.OS === 'ios' ? '700' : 'bold',
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  backLink: {
    marginTop: 12,
  },
  backText: {
    fontFamily: typography.regular,
    color: "rgba(255,255,255,0.85)",
    fontSize: 15,
  },
  footer: {
    position: "absolute",
    bottom: 50,  
    width: "100%",  
    maxWidth: 380,  
    alignSelf: "center",  
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.18)",
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
  },
  footerText: {
    fontFamily: typography.medium,
    fontSize: 17,
    color: "#3a495aff",
    fontWeight: Platform.OS === 'ios' ? '600' : 'bold',
  },
  footerSeparator: {
    fontSize: 20,  
    color: "rgba(255,255,255,0.7)",
    marginHorizontal: 18,
  },
});